---
# file: roles/jupyter/vars/main.yml
jupyter_pkgs:
  - git
  - npm
  - python
  - python-dev
  - python-setuptools
  - python3
  - python3-dev
  - python3-pip
  - python3-setuptools
  - sudo
  - apt-transport-https

