---
- hosts: mongo

  vars_prompt:
    - name: "jupyterpw"
      prompt: "Please enter a password for the Jupyter user. Press enter to use no password."
      private: yes
      confirm: yes
      encrypt: "sha512_crypt"

  vars:
    nossl: True

  roles:
    - jupyter
